CREATE TABLE IF NOT EXISTS item_bulk_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  action text NOT NULL CHECK (action IN ('retry', 'retry_from_facts')),
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled')),
  matched_count integer NOT NULL DEFAULT 0,
  processed_count integer NOT NULL DEFAULT 0,
  queued_count integer NOT NULL DEFAULT 0,
  skipped_count integer NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS item_bulk_job_items (
  job_id uuid NOT NULL REFERENCES item_bulk_jobs(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  position bigint GENERATED BY DEFAULT AS IDENTITY,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'processed', 'skipped', 'failed')),
  error_message text,
  processed_at timestamptz,
  PRIMARY KEY (job_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_item_bulk_jobs_user_created ON item_bulk_jobs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_item_bulk_job_items_next ON item_bulk_job_items(job_id, status, position);
