UPDATE user_settings
SET facts_model = CASE WHEN facts_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE facts_model END,
    facts_secondary_model = CASE WHEN facts_secondary_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE facts_secondary_model END,
    facts_fallback_model = CASE WHEN facts_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE facts_fallback_model END,
    summary_model = CASE WHEN summary_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE summary_model END,
    summary_secondary_model = CASE WHEN summary_secondary_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE summary_secondary_model END,
    summary_fallback_model = CASE WHEN summary_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE summary_fallback_model END,
    digest_cluster_model = CASE WHEN digest_cluster_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE digest_cluster_model END,
    digest_model = CASE WHEN digest_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE digest_model END,
    ask_model = CASE WHEN ask_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE ask_model END,
    source_suggestion_model = CASE WHEN source_suggestion_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE source_suggestion_model END,
    facts_check_model = CASE WHEN facts_check_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE facts_check_model END,
    facts_check_fallback_model = CASE WHEN facts_check_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE facts_check_fallback_model END,
    faithfulness_check_model = CASE WHEN faithfulness_check_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE faithfulness_check_model END,
    faithfulness_check_fallback_model = CASE WHEN faithfulness_check_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE faithfulness_check_fallback_model END,
    navigator_model = CASE WHEN navigator_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE navigator_model END,
    navigator_fallback_model = CASE WHEN navigator_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE navigator_fallback_model END,
    ai_navigator_brief_model = CASE WHEN ai_navigator_brief_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE ai_navigator_brief_model END,
    ai_navigator_brief_fallback_model = CASE WHEN ai_navigator_brief_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE ai_navigator_brief_fallback_model END,
    audio_briefing_script_model = CASE WHEN audio_briefing_script_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE audio_briefing_script_model END,
    audio_briefing_script_fallback_model = CASE WHEN audio_briefing_script_fallback_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE audio_briefing_script_fallback_model END,
    tts_markup_preprocess_model = CASE WHEN tts_markup_preprocess_model = 'deepseek-flash' THEN 'deepseek-v4-flash' ELSE tts_markup_preprocess_model END
WHERE 'deepseek-flash' IN (
    facts_model,
    facts_secondary_model,
    facts_fallback_model,
    summary_model,
    summary_secondary_model,
    summary_fallback_model,
    digest_cluster_model,
    digest_model,
    ask_model,
    source_suggestion_model,
    facts_check_model,
    facts_check_fallback_model,
    faithfulness_check_model,
    faithfulness_check_fallback_model,
    navigator_model,
    navigator_fallback_model,
    ai_navigator_brief_model,
    ai_navigator_brief_fallback_model,
    audio_briefing_script_model,
    audio_briefing_script_fallback_model,
    tts_markup_preprocess_model
);
