#!/bin/sh
set -eu

if [ -n "${GOOGLE_SERVICE_ACCOUNT_JSON:-}" ]; then
  GOOGLE_APPLICATION_CREDENTIALS_PATH="${GOOGLE_APPLICATION_CREDENTIALS:-/tmp/google-service-account.json}"
  umask 077
  printf '%s' "$GOOGLE_SERVICE_ACCOUNT_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS_PATH"
  export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS_PATH"
fi

exec "$@"
